# Platform.sh application configuration
name: 'rammerhead'
type: 'nodejs:18'

web:
  commands:
    start: 'npm start'
  locations:
    '/':
      passthru: true

disk: 512

build:
  flavor: none

hooks:
  build: |
    # Skip problematic preinstall script and install dependencies
    npm install --ignore-scripts
    # Run any necessary post-install steps manually if needed
    npm rebuild

variables:
  env:
    NODE_ENV: 'production'
    PORT: 8080

mounts:
  'logs':
    source: local
    source_path: logs
  'tmp':
    source: local
    source_path: tmp
